### ISSUE TITLE
Quantile loss

### ISSUE THREAD

**Issue by mhoward2718** [foges/pogs#32]
Roger Koenker has mentioned POGS as a good choice for solving large scale quantile regression problems. In one paper he mentions that he has ran some experiments with the GPU implementation of POGS.

How can one apply POGS to quantile regression? Were Koenker's experiments using an unpublished POGS implementation of quantile loss? Or is it possible to to define a quantile regression problem using the 16 available functions in `prox_lib.sh`?

Otherwise, I'd love a bit of direction on how to implement quantile loss in POGS.

**Comment by foges** [comment]
Hi Howard, this answer surely comes too late, but I figured I'd leave it here for others that might be interested:

The quantile regression problem can be defined as

```
minimize_{x} \sum_i (1/2) |a_i x - b_i| + (\tau  - 1/2) (a_i x - b_i)
```

where `a_i` and `b_i` are your data.

This fits nicely with POGS if you use `f` as the absolute value and `g` as zero. The expression becomes  `f = (1/2) |y_i - b_i| + (\tau - 1/2) y_i` and `g` is zero, where `y_i = a_i x`. Note that the term `(\tau - 1/2) b_i` has been left out since it's not relevant to the minimization since it's constant. 

Here is an example of how you'd set it up in C++

```
  const T tau = static_cast<T>(0.2);

  f.reserve(m);
  for (unsigned int i = 0; i < m; ++i)
    f.emplace_back(
      kAbs,
      static_cast<T>(1), 
      b[i], 
      static_cast<T>(1), 
      static_cast<T>(tau - static_cast<T>(0.5)));

  g.reserve(n);
  for (unsigned int i = 0; i < n; ++i)
    g.emplace_back(kZero);
```

I'll add an example to the C++ examples directory.
